Revert Kong ingress upgrade due to an error we see.
```
Error: failed to wait for KongV1Alpha1IngressClassParameters caches to sync: timed out waiting for cache to be synced
```

https://discuss.konghq.com/t/kong-ingress-crontroller-in-dbless-mode-error-failed-to-wait-for-secret-caches-to-sync-timed-out-waiting-for-cache-to-be-synced/9923

Seems similar too.